name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Bun ğŸ
        uses: oven-sh/setup-bun@v2
      - name: Install and Build ğŸ”§
        run: |
          bun install --frozen-lockfile
          bun run build
      - name: Create blog branch ğŸŒ¿
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/blog/dist/
          publish_branch: blog
          force_orphan: true
          commit_message: ":rocket: deploy: "
          user_name: "github-actions"
          user_email: "github-actions@github.com"
      - name: Create slides branch ğŸŒ¿
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/slides/dist/
          publish_branch: slides
          force_orphan: true
          commit_message: ":rocket: deploy: "
          user_name: "github-actions"
          user_email: "github-actions@github.com"
      - name: Create root domain branch ğŸŒ¿
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/root/dist/
          publish_branch: root
          force_orphan: true
          commit_message: ":rocket: deploy: "
          user_name: "github-actions"
          user_email: "github-actions@github.com"
